apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: app-backend
 namespace: default
 labels:
    app: app-backend
spec:
  minReplicas: 6
  maxReplicas: 10  
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: app-backend